# Uncomment this file to enable multilanguage site support

[en]
languageName = "English"
languagedirection = "ltr"
title = "Sun Tree"
weight = 1

[zh-cn]
languageName = "简体中文"
languagedirection = "ltr"
title = "昱树"
weight = 2
